import json
import os
import sys

from api_client import make_post_request, get_groq_api_key as get_api_key, call_groq_api


# ==============================================================================
# SECTION 1: Load Gap Analysis Content from gap_analysis.txt
# ==============================================================================
# Reads the gap_analysis.txt file generated by gap_analysis.py.
def load_gap_analysis(filename="gap_analysis.txt"):
    script_dir = os.path.dirname(os.path.abspath(__file__))
    file_path = os.path.join(script_dir, filename)
    
    if not os.path.exists(file_path):
        print(f"Error: Could not find '{filename}' at {file_path}")
        print("Please run gap_analysis.py first to generate gap_analysis.txt.")
        return None
        
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()
        return content
    except Exception as e:
        print(f"Error reading '{filename}': {e}")
        return None


# ==============================================================================
# SECTION 2: Build Structured Prompt for Research Title Generation
# ==============================================================================
# Formats the prompt instructing Gemini to turn the 5 research gaps into 5 actionable
# candidate paper titles tailored for a solo researcher.
def build_title_prompt(gap_text):
    prompt_text = (
        "You are an expert medical research mentor helping a independent/solo researcher design achievable study concepts. "
        "Below is a gap analysis report generated from recent PubMed literature on Diabetic Ketoacidosis (DKA).\n\n"
        "==================== GAP ANALYSIS REPORT ====================\n\n"
        f"{gap_text}\n\n"
        "=============================================================\n\n"
        "TASK:\n"
        "Based on the research gaps in the report above, generate exactly 5 candidate research paper titles — "
        "one title for each of the 5 research gaps. For EACH candidate title, provide the following 4 structured details:\n\n"
        "1. Proposed Title: (A clear, professional academic paper title)\n"
        "2. Target Gap & PMIDs: (Specify which gap and PMIDs from the report this title directly addresses)\n"
        "3. Suggested Study Design: (e.g. Systematic Review & Meta-Analysis, Retrospective Electronic Health Record Cohort, "
        "Public Genomic/Metagenomic Secondary Analysis, Case Series & Narrative Synthesis)\n"
        "4. Solo Researcher Feasibility Note: (A realistic feasibility assessment explaining what specific open-access datasets, "
        "public databases, electronic records, or literature tools a solo researcher without major clinical trial funding would need to execute it)\n\n"
        "Format the output cleanly with clear numbering (1 to 5) and markdown headers."
    )
    return prompt_text


# ==============================================================================
# SECTION 3: Send Request to Groq API (llama-3.3-70b-versatile)
# ==============================================================================
# Uses call_groq_api imported from api_client.py.


# ==============================================================================
# SECTION 4: Save Generated Titles to File
# ==============================================================================
# Saves the generated candidate titles to 'research_titles.txt' in the script folder.
def save_research_titles(text, filename="research_titles.txt"):
    script_dir = os.path.dirname(os.path.abspath(__file__))
    file_path = os.path.join(script_dir, filename)
    
    try:
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(text)
        return True, file_path
    except IOError as e:
        print(f"Error saving file '{filename}': {e}")
        return False, None


# ==============================================================================
# SECTION 5: Main Script Flow
# ==============================================================================
def main():
    print("==================================================")
    print("      PubMed Research Title Generator Tool        ")
    print("==================================================")
    
    # Step 1: Load gap_analysis.txt
    gap_text = load_gap_analysis("gap_analysis.txt")
    if not gap_text:
        return
        
    print("Successfully loaded gap_analysis.txt.")
    
    # Step 2: Get API key
    api_key = get_api_key()
    if not api_key:
        print("Error: GROQ_API_KEY is required.")
        return
        
    # Step 3: Build prompt
    prompt = build_title_prompt(gap_text)
    
    # Step 4: Call Groq API
    titles_result = call_groq_api(prompt, api_key)
    
    if not titles_result:
        print("\nFailed to generate research titles.")
        return
        
    # Step 5: Save to research_titles.txt
    success, output_path = save_research_titles(titles_result, "research_titles.txt")
    
    # Step 6: Print results to terminal
    print("\n==================================================")
    print("            CANDIDATE RESEARCH TITLES             ")
    print("==================================================")
    print(titles_result)
    print("==================================================")
    if success:
        print(f"Research titles successfully saved to: {output_path}")
        print("==================================================")


if __name__ == "__main__":
    main()
